### PR TITLE
Tor obfs4 bridges

### PR DESCRIPTION
**Pull request by skrashevich**
Added support for obfs4 bridges through the environment variable

### CODE REVIEW

**Review by avpnusr — APPROVED** [review]
Looks perfekt, thank you!

**Comment by r35p3ct** [comment]
> > Am I adding variables correctly?
> 
> no

Tell me how to add a bridge correctly.

**Comment by crnah2o** [comment]
> > Am I adding variables correctly?
> 
> no

Would you be so kind as to help us with the correct form to set variable(s)? Thanks in advance.

**Comment by crnah2o** [comment]
> > > Am I adding variables correctly?
> > 
> > 
> > no
> 
> Tell me how to add a bridge correctly.

Did you manage to do it?

**Pull request merged**
